fau_queries = [
    # General Information & Rankings
    "FAU Erlangen Nürnberg overview",
    "FAU Erlangen Nürnberg world ranking 2025",
    "FAU Erlangen Nürnberg QS ranking",
    "Is FAU Erlangen a good university?",
    "FAU Erlangen vs TU Munich comparison",
    "FAU Erlangen acceptance rate",
    "FAU Erlangen tuition fees for international students",
    "FAU Erlangen admission requirements for master’s",
    "FAU Erlangen international student population",
    "FAU Nürnberg and Erlangen campus difference",

    # Academics & Programs
    "FAU Erlangen master’s programs taught in English",
    "FAU Erlangen bachelor's programs",
    "FAU Erlangen PhD opportunities",
    "FAU Erlangen medicine program details",
    "FAU Erlangen computer science courses",
    "FAU Erlangen MBA program",
    "FAU Erlangen AI study program",
    "FAU Erlangen data science course details",
    "FAU Erlangen engineering programs",
    "Best programs to study at FAU Erlangen",

    # Research & Labs
    "FAU Erlangen research labs list",
    "FAU Erlangen AI research labs",
    "FAU Erlangen materials science research",
    "FAU Erlangen biomedical engineering lab",
    "FAU Erlangen photonics research",
    "FAU Erlangen Fraunhofer partnerships",
    "FAU Erlangen Max Planck collaboration",
    "FAU Erlangen Helmholtz Institute projects",
    "FAU Erlangen nanotechnology research",
    "FAU Erlangen climate research centers",

    # Infrastructure & Facilities
    "FAU Erlangen campus tour",
    "FAU Erlangen library hours",
    "FAU Erlangen computing center",
    "FAU Erlangen Nürnberg campus map",
    "FAU Erlangen sports facilities",
    "FAU Erlangen innovation lab",
    "FAU Erlangen technical equipment",
    "FAU Erlangen canteen reviews",
    "FAU Erlangen lecture hall facilities",
    "FAU Erlangen student housing options",

    # Faculties & Departments
    "Faculty of Engineering FAU Erlangen",
    "Faculty of Medicine FAU Erlangen",
    "Faculty of Sciences FAU Erlangen",
    "FAU Erlangen Faculty of Business, Economics and Law",
    "FAU Erlangen Department of Computer Science",
    "FAU Erlangen Institute of Materials Science",
    "FAU Erlangen Faculty of Humanities and Theology",
    "FAU Erlangen Chair of Artificial Intelligence",
    "FAU Erlangen Institute of Geography",
    "FAU Erlangen Chemistry department labs",

    # International Students
    "FAU Erlangen international student guide",
    "FAU Erlangen visa support services",
    "FAU Erlangen orientation for new students",
    "FAU Erlangen buddy program",
    "FAU Erlangen Erasmus partner universities",
    "FAU Erlangen language courses for internationals",
    "FAU Erlangen international office contact",
    "FAU Erlangen accommodation for international students",
    "FAU Erlangen cultural integration support",
    "FAU Erlangen student exchange programs",

    # Careers & Alumni
    "FAU Erlangen career services office",
    "FAU Erlangen internship opportunities",
    "FAU Erlangen job portal",
    "FAU Erlangen alumni network",
    "FAU Erlangen startup incubators",
    "FAU Erlangen entrepreneurship support",
    "FAU Erlangen industry collaborations",
    "FAU Erlangen LinkedIn alumni insights",
    "FAU Erlangen DAAD alumni stories",
    "FAU Erlangen graduate employment rate",

    # Academic Life
    "FAU Erlangen academic calendar 2025",
    "FAU Erlangen semester start dates",
    "FAU Erlangen exam schedule",
    "FAU Erlangen grading system",
    "FAU Erlangen ECTS credits system",
    "FAU Erlangen lecture attendance policy",
    "FAU Erlangen course registration process",
    "FAU Erlangen thesis submission rules",
    "FAU Erlangen Moodle guide",
    "FAU Erlangen online learning platforms",

    # Student Life
    "FAU Erlangen student associations",
    "FAU Erlangen student union services",
    "FAU Erlangen student life in Erlangen",
    "FAU Erlangen cost of living",
    "FAU Erlangen part-time job opportunities",
    "FAU Erlangen student discount options",
    "FAU Erlangen clubs and societies",
    "FAU Erlangen cultural events",
    "FAU Erlangen student testimonials",
    "FAU Erlangen mental health services",

    # Admission & Application
    "How to apply to FAU Erlangen master's program",
    "FAU Erlangen Uni-Assist application",
    "FAU Erlangen admission deadlines",
    "FAU Erlangen English language requirements",
    "FAU Erlangen SOP and LOR tips",
    "FAU Erlangen credit transfer policy",
    "FAU Erlangen scholarship opportunities",
    "FAU Erlangen DAAD-funded programs",
    "FAU Erlangen pre-departure checklist",
    "FAU Erlangen online application portal",

    # Location & Living
    "Living in Erlangen as a student",
    "Best areas to live near FAU Erlangen",
    "FAU Erlangen transportation guide",
    "FAU Erlangen Nürnberg campus amenities",
    "Things to do around FAU Erlangen",
    "Cost of living in Erlangen for students",
    "FAU Erlangen student housing application",
    "Student visa checklist for FAU Erlangen",
    "Public transport ticket FAU students",
    "Weather and climate in Erlangen"
]
